backend:
  name: git-gateway
  branch: main   # GitHub 기본 브랜치

media_folder: "lab/assets/images"   # 업로드 파일 저장 경로 (repo 안)
public_folder: "/assets/images"     # 사이트에서 접근할 경로

collections:
  # Professors
  - name: "professors"
    label: "Professors"
    file: "lab/data/members/professors.json"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - name: "education"
        label: "Education"
        widget: "list"
        fields:
      - { name: "degree", label: "Degree", widget: "string" }
      - { name: "experience", label: "Professional Experience", widget: "text" }
      - { name: "image", label: "Photo", widget: "image" }

  # Students
  - name: "students"
    label: "Students"
    file: "lab/data/members/students.json"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "degree", label: "Degree", widget: "select", options: ["PhD", "Master", "Undergraduate"] }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "email", label: "Email", widget: "string" }
      - { name: "image", label: "Photo", widget: "image" }

  # Alumni
  - name: "alumni"
    label: "Alumni"
    file: "lab/data/members/alumni.json"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "degree", label: "Degree", widget: "string" }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "email", label: "Email", widget: "string", required: false }
      - { name: "image", label: "Photo", widget: "image", required: false }

  # Publications - Journals
  - name: "journals"
    label: "Journal Publications"
    file: "lab/data/publications/journals.json"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - name: "authors"
        label: "Authors"
        widget: "list"
        fields:
          - { name: "author", label: "Author", widget: "string" }
      - { name: "journal", label: "Journal", widget: "string" }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "link", label: "Link", widget: "string", required: false }

  # Publications - Patents
  - name: "patents"
    label: "Patents"
    file: "lab/data/publications/patents.json"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - name: "inventors"
        label: "Inventors"
        widget: "list"
        fields:
          - { name: "inventor", label: "Inventor", widget: "string" }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "patent_no", label: "Patent Number", widget: "string", required: false }
      - { name: "link", label: "Link", widget: "string", required: false }

  # Projects
  - name: "projects"
    label: "Projects"
    file: "lab/data/projects.json"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "members", label: "Members", widget: "list", field: { name: "member", label: "Member", widget: "string" } }
      - { name: "year", label: "Year", widget: "number" }
      - { name: "image", label: "Image", widget: "image", required: false }

  # Contacts
  - name: "contacts"
    label: "Contacts"
    file: "lab/data/contacts.json"
    fields:
      - { name: "lab_name", label: "Lab Name", widget: "string" }
      - { name: "address", label: "Address", widget: "string" }
      - { name: "email", label: "Email", widget: "string" }
      - { name: "phone", label: "Phone", widget: "string", required: false }
      - { name: "map_link", label: "Map Link", widget: "string", required: false }
